[package]
name = "error-code"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
error-code-derive = { workspace = true }

[dev-dependencies]
thiserror = { workspace = true }
http = { workspace = true }
